
import java.awt.Color;
import java.awt.Component;
import javax.swing.JScrollPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jiepastor
 */
public class f_mainpage extends javax.swing.JFrame {

    /**
     * Creates new form f_mainpage
     */
    public f_mainpage() {
        initComponents();
        selectButton(MENU.BALANCE_INQUIRY);

        for(int i=0;i<4;i++)
        {
            tp.setEnabledAt(i, false);
        }
    }
    
    public enum MENU{
        BALANCE_INQUIRY,
        FUNDS_TRANSFER,
        TRANSACTIONS_HISTORY,
        ACCOUNT_SETTINGS
    };
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        tp = new javax.swing.JTabbedPane();
        tp_balance = new javax.swing.JPanel();
        tp_b_scrollpane = new javax.swing.JScrollPane();
        tp_b_table = new javax.swing.JTable();
        tp_funds = new javax.swing.JPanel();
        tp_f_lbl_amount = new javax.swing.JLabel();
        tp_f_lbl_source = new javax.swing.JLabel();
        tp_f_lbl_dest = new javax.swing.JLabel();
        tp_f_t_dest = new javax.swing.JTextField();
        tp_f_t_amount = new javax.swing.JTextField();
        tp_f_t_source = new javax.swing.JComboBox<>();
        tp_f_scrollpane = new javax.swing.JScrollPane();
        tp_f_t_notes = new javax.swing.JTextArea();
        tp_f_lbl_notes = new javax.swing.JLabel();
        tp_f_btn_confirm = new javax.swing.JButton();
        tp_trans = new javax.swing.JPanel();
        tp_t_scrollpane = new javax.swing.JScrollPane();
        tp_t_table = new javax.swing.JTable();
        tp_t_spin_from_day = new javax.swing.JSpinner();
        tp_t_spin_from_month = new javax.swing.JSpinner();
        tp_t_spin_from_year = new javax.swing.JSpinner();
        tp_t_lbl_from = new javax.swing.JLabel();
        tp_t_lbl_to = new javax.swing.JLabel();
        tp_t_spin_to_month = new javax.swing.JSpinner();
        tp_t_spin_to_day = new javax.swing.JSpinner();
        tp_t_spin_to_year = new javax.swing.JSpinner();
        tp_t_btn_set = new javax.swing.JButton();
        tp_settings = new javax.swing.JPanel();
        tp_s_name = new javax.swing.JLabel();
        tp_s_user = new javax.swing.JLabel();
        tp_s_btn_info = new javax.swing.JButton();
        tp_s_btn_pass = new javax.swing.JButton();
        tp_s_btn_about = new javax.swing.JButton();
        tp_s_btn_logout = new javax.swing.JButton();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BBC Banking Services");

        jpanel.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(239, 239, 239));

        tp.setBackground(new java.awt.Color(255, 255, 255));

        tp_balance.setBackground(new java.awt.Color(255, 255, 255));

        tp_b_scrollpane.setBackground(new java.awt.Color(255, 255, 255));

        tp_b_table.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_b_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BANK", "ACCT NO", "ACCT TYPE", "STATUS", "BALANCE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tp_b_table.setGridColor(new java.awt.Color(255, 255, 255));
        tp_b_table.setRowHeight(30);
        tp_b_scrollpane.setViewportView(tp_b_table);

        javax.swing.GroupLayout tp_balanceLayout = new javax.swing.GroupLayout(tp_balance);
        tp_balance.setLayout(tp_balanceLayout);
        tp_balanceLayout.setHorizontalGroup(
            tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_balanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_b_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
                .addContainerGap())
        );
        tp_balanceLayout.setVerticalGroup(
            tp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_balanceLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(tp_b_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );

        tp.addTab("balance inquiry", tp_balance);

        tp_funds.setBackground(new java.awt.Color(255, 255, 255));

        tp_f_lbl_amount.setText("AMOUNT:");

        tp_f_lbl_source.setText("SOURCE ACCOUNT:");

        tp_f_lbl_dest.setText("DESTINATION ACCOUNT:");

        tp_f_t_dest.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tp_f_t_amount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tp_f_t_source.setBackground(new java.awt.Color(247, 247, 247));
        tp_f_t_source.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_f_t_source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1234567890 - SAVINGS", "0987654321 - CHECKING" }));

        tp_f_t_notes.setColumns(20);
        tp_f_t_notes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_f_t_notes.setRows(5);
        tp_f_scrollpane.setViewportView(tp_f_t_notes);

        tp_f_lbl_notes.setText("NOTES:");

        tp_f_btn_confirm.setBackground(new java.awt.Color(2, 117, 216));
        tp_f_btn_confirm.setForeground(new java.awt.Color(255, 255, 255));
        tp_f_btn_confirm.setText("CONFIRM");

        javax.swing.GroupLayout tp_fundsLayout = new javax.swing.GroupLayout(tp_funds);
        tp_funds.setLayout(tp_fundsLayout);
        tp_fundsLayout.setHorizontalGroup(
            tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_fundsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_fundsLayout.createSequentialGroup()
                        .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_f_lbl_notes)
                            .addComponent(tp_f_lbl_amount))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tp_fundsLayout.createSequentialGroup()
                        .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tp_f_btn_confirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tp_f_scrollpane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_f_t_amount)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tp_fundsLayout.createSequentialGroup()
                                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tp_f_lbl_source)
                                    .addComponent(tp_f_t_source, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tp_f_lbl_dest)
                                    .addComponent(tp_f_t_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))))
        );
        tp_fundsLayout.setVerticalGroup(
            tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_fundsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tp_f_lbl_source)
                    .addComponent(tp_f_lbl_dest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tp_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tp_f_t_source, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tp_f_t_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tp_f_lbl_amount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_f_t_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tp_f_lbl_notes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp_f_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tp_f_btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp.addTab("funds transfer", tp_funds);

        tp_trans.setBackground(new java.awt.Color(255, 255, 255));

        tp_t_table.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_t_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DI KO ALAM", "YUNG MGA DATA", "COLUMNS DITO", "EDIT NYO NLNG"
            }
        ));
        tp_t_table.setRowHeight(30);
        tp_t_scrollpane.setViewportView(tp_t_table);

        tp_t_spin_from_day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_from_month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_from_year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_lbl_from.setText("FROM:");

        tp_t_lbl_to.setText("TO:");

        tp_t_spin_to_month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_to_day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_spin_to_year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp_t_btn_set.setBackground(new java.awt.Color(2, 117, 216));
        tp_t_btn_set.setForeground(new java.awt.Color(255, 255, 255));
        tp_t_btn_set.setText("SET");

        javax.swing.GroupLayout tp_transLayout = new javax.swing.GroupLayout(tp_trans);
        tp_trans.setLayout(tp_transLayout);
        tp_transLayout.setHorizontalGroup(
            tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_transLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp_t_scrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
                    .addGroup(tp_transLayout.createSequentialGroup()
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tp_transLayout.createSequentialGroup()
                                .addComponent(tp_t_lbl_from)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tp_t_spin_from_month, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tp_t_spin_from_day, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tp_t_spin_from_year, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tp_transLayout.createSequentialGroup()
                                .addComponent(tp_t_lbl_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tp_t_spin_to_month, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tp_t_spin_to_day, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tp_t_spin_to_year, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(tp_t_btn_set, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tp_transLayout.setVerticalGroup(
            tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_transLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tp_transLayout.createSequentialGroup()
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tp_t_spin_from_day, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_from_month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_from_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tp_transLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(tp_t_lbl_from)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tp_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tp_t_spin_to_day, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_to_month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tp_t_spin_to_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tp_transLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(tp_t_lbl_to))))
                    .addComponent(tp_t_btn_set, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(tp_t_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp.addTab("transaction history", tp_trans);

        tp_settings.setBackground(new java.awt.Color(255, 255, 255));

        tp_s_name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_name.setText("LAST, FIRST (MIDDLE)");

        tp_s_user.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        tp_s_user.setText("username");

        tp_s_btn_info.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_info.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_info.setText("VIEW INFORMATION");

        tp_s_btn_pass.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_pass.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_pass.setText("CHANGE PASSWORD");

        tp_s_btn_about.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_about.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_about.setText("ABOUT");

        tp_s_btn_logout.setBackground(new java.awt.Color(222, 222, 222));
        tp_s_btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tp_s_btn_logout.setText("LOG OUT");

        javax.swing.GroupLayout tp_settingsLayout = new javax.swing.GroupLayout(tp_settings);
        tp_settings.setLayout(tp_settingsLayout);
        tp_settingsLayout.setHorizontalGroup(
            tp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_settingsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp_s_btn_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tp_settingsLayout.createSequentialGroup()
                        .addGroup(tp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp_s_user)
                            .addComponent(tp_s_name))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tp_s_btn_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                    .addComponent(tp_s_btn_about, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                    .addComponent(tp_s_btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        tp_settingsLayout.setVerticalGroup(
            tp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_settingsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tp_s_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_s_user)
                .addGap(18, 18, 18)
                .addComponent(tp_s_btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_s_btn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_s_btn_about, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_s_btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        tp.addTab("account settings", tp_settings);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp)
        );

        logoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO2.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, Short.MAX_VALUE)
        );

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setForeground(new java.awt.Color(102, 102, 102));
        btn1.setText("BALANCE INQUIRY");
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setForeground(new java.awt.Color(102, 102, 102));
        btn2.setText("FUND TRANSFER");
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setForeground(new java.awt.Color(102, 102, 102));
        btn3.setText("TRANS HISTORY");
        btn3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setForeground(new java.awt.Color(102, 102, 102));
        btn4.setText("ACCT SETTINGS");
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(681, 681, 681))))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        selectButton(MENU.BALANCE_INQUIRY);
        tp.setSelectedComponent(tp_balance);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        selectButton(MENU.FUNDS_TRANSFER);
        tp.setSelectedComponent(tp_funds);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        selectButton(MENU.TRANSACTIONS_HISTORY);
        tp.setSelectedComponent(tp_trans);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        selectButton(MENU.ACCOUNT_SETTINGS);
        tp.setSelectedComponent(tp_settings);
    }//GEN-LAST:event_btn4ActionPerformed

    void selectButton(MENU m){
        
        btn1.setBackground(Color.white);
        btn1.setForeground(Color.black);
        btn2.setBackground(Color.white);
        btn2.setForeground(Color.black);
        btn3.setBackground(Color.white);
        btn3.setForeground(Color.black);
        btn4.setBackground(Color.white);
        btn4.setForeground(Color.black);
        float[] val = new float[3];
        Color.RGBtoHSB(2, 117, 216, val);
        
        Color c = Color.getHSBColor(val[0], val[1], val[2]);
        
        switch (m){
            case BALANCE_INQUIRY:
                btn1.setBackground(c);
                btn1.setForeground(Color.white);
                break;
            case FUNDS_TRANSFER:
                btn2.setBackground(c);
                btn2.setForeground(Color.white);
                break;
            case TRANSACTIONS_HISTORY:
                btn3.setBackground(c);
                btn3.setForeground(Color.white);
                break;
            case ACCOUNT_SETTINGS:
                btn4.setBackground(c);
                btn4.setForeground(Color.white);
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane tp;
    private javax.swing.JScrollPane tp_b_scrollpane;
    private javax.swing.JTable tp_b_table;
    private javax.swing.JPanel tp_balance;
    private javax.swing.JButton tp_f_btn_confirm;
    private javax.swing.JLabel tp_f_lbl_amount;
    private javax.swing.JLabel tp_f_lbl_dest;
    private javax.swing.JLabel tp_f_lbl_notes;
    private javax.swing.JLabel tp_f_lbl_source;
    private javax.swing.JScrollPane tp_f_scrollpane;
    private javax.swing.JTextField tp_f_t_amount;
    private javax.swing.JTextField tp_f_t_dest;
    private javax.swing.JTextArea tp_f_t_notes;
    private javax.swing.JComboBox<String> tp_f_t_source;
    private javax.swing.JPanel tp_funds;
    private javax.swing.JButton tp_s_btn_about;
    private javax.swing.JButton tp_s_btn_info;
    private javax.swing.JButton tp_s_btn_logout;
    private javax.swing.JButton tp_s_btn_pass;
    private javax.swing.JLabel tp_s_name;
    private javax.swing.JLabel tp_s_user;
    private javax.swing.JPanel tp_settings;
    private javax.swing.JButton tp_t_btn_set;
    private javax.swing.JLabel tp_t_lbl_from;
    private javax.swing.JLabel tp_t_lbl_to;
    private javax.swing.JScrollPane tp_t_scrollpane;
    private javax.swing.JSpinner tp_t_spin_from_day;
    private javax.swing.JSpinner tp_t_spin_from_month;
    private javax.swing.JSpinner tp_t_spin_from_year;
    private javax.swing.JSpinner tp_t_spin_to_day;
    private javax.swing.JSpinner tp_t_spin_to_month;
    private javax.swing.JSpinner tp_t_spin_to_year;
    private javax.swing.JTable tp_t_table;
    private javax.swing.JPanel tp_trans;
    // End of variables declaration//GEN-END:variables
}
